In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("diabetes.csv")
df.head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0

In [5]:
df.head(10)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0
5,1008,248.0,94,69.0,3.6,4.81,Buckingham,34,male,71.0,190.0,large,132.0,86.0,36.0,42.0
6,1011,195.0,92,41.0,4.8,4.84,Buckingham,30,male,69.0,191.0,medium,161.0,112.0,46.0,49.0
7,1015,227.0,75,44.0,5.2,3.94,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,34.0,39.0
8,1016,177.0,87,49.0,3.6,4.84,Buckingham,45,male,69.0,166.0,large,160.0,80.0,34.0,40.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,45.0,50.0

In [6]:
df.tail()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,35.0,39.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,32.0,43.0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,33.0,40.0
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,41.0,48.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,49.0,58.0

In [7]:
df.sample(5)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
235,17754,204.0,89,56.0,3.6,5.02,Louisa,48,male,68.0,196.0,medium,170.0,96.0,38.0,42.0
85,4759,206.0,85,46.0,4.5,4.82,Louisa,67,male,67.0,178.0,large,119.0,68.0,37.0,41.0
274,20260,179.0,75,36.0,5.0,4.75,Buckingham,23,female,65.0,183.0,medium,120.0,80.0,43.0,45.0
215,15805,197.0,92,46.0,4.3,4.75,Buckingham,36,female,64.0,136.0,small,NaN,NaN,32.0,37.0
56,2765,204.0,128,61.0,3.3,5.20,Buckingham,62,male,68.0,180.0,large,141.0,81.0,38.0,41.0

In [8]:
df.head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0

In [12]:
df.loc[10] # Row of data at index 10

id            1024
chol         242.0
stab.glu        82
hdl           54.0
ratio          4.5
glyhb         4.77
location    Louisa
age             60
gender      female
height        65.0
weight       156.0
frame       medium
bp.1s        130.0
bp.1d         90.0
waist         39.0
hip           45.0
Name: 10, dtype: object

In [16]:
df.loc[50:]

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
50,2754,196.0,82,58.0,3.4,4.250000,Buckingham,76,male,65.0,154.0,NaN,158.0,78.0,37.0,41.0
51,2756,237.0,87,41.0,5.8,5.350000,Buckingham,43,female,64.0,181.0,medium,104.0,90.0,36.0,46.0
52,2757,212.0,97,45.0,4.7,6.330000,Buckingham,65,female,61.0,187.0,large,158.0,94.0,43.0,47.0
53,2758,233.0,92,39.0,6.0,4.560000,Buckingham,45,female,64.0,167.0,large,124.0,86.0,39.0,44.0
54,2762,289.0,111,50.0,5.8,9.390000,Buckingham,70,female,60.0,220.0,medium,126.0,80.0,51.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,35.0,39.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,32.0,43.0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,33.0,40.0
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,41.0,48.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,49.0,58.0

In [18]:
df[['id', 'age']]

        id  age
0     1000   46
1     1001   29
2     1002   58
3     1003   67
4     1005   64
..     ...  ...
398  41506   53
399  41507   51
400  41510   29
401  41752   41
402  41756   68

[403 rows x 2 columns]

In [20]:
df[['id', 'age']].loc[0:5]

     id  age
0  1000   46
1  1001   29
2  1002   58
3  1003   67
4  1005   64
5  1008   34

# Concat Examples

In [21]:
df1 = df[['id', 'age', 'gender']].loc[0:2]
df1

     id  age  gender
0  1000   46  female
1  1001   29  female
2  1002   58  female

In [22]:
df2 = df[['id', 'age', 'gender']].loc[3:5]
df2

     id  age gender
3  1003   67   male
4  1005   64   male
5  1008   34   male

In [23]:
df3 = pd.concat([df1, df2], axis=0) # Concat by rows
df3

     id  age  gender
0  1000   46  female
1  1001   29  female
2  1002   58  female
3  1003   67    male
4  1005   64    male
5  1008   34    male

In [24]:
df4 = pd.concat([df2, df1], axis=0) # Concat by rows
df4

     id  age  gender
3  1003   67    male
4  1005   64    male
5  1008   34    male
0  1000   46  female
1  1001   29  female
2  1002   58  female

In [25]:
df5 = df[['id', 'age', 'gender']].loc[0:3]
df5

     id  age  gender
0  1000   46  female
1  1001   29  female
2  1002   58  female
3  1003   67    male

In [26]:
df6 = df[['chol', 'weight', 'frame']].loc[0:3]
df6

    chol  weight   frame
0  203.0   121.0  medium
1  165.0   218.0   large
2  228.0   256.0   large
3   78.0   119.0   large

In [28]:
df7 = pd.concat([df5, df6], axis = 1)
df7

     id  age  gender   chol  weight   frame
0  1000   46  female  203.0   121.0  medium
1  1001   29  female  165.0   218.0   large
2  1002   58  female  228.0   256.0   large
3  1003   67    male   78.0   119.0   large

# Merge Examples

In [29]:
patient_df = df[['id', 'age', 'gender']].loc[0:5]
patient_df

     id  age  gender
0  1000   46  female
1  1001   29  female
2  1002   58  female
3  1003   67    male
4  1005   64    male
5  1008   34    male

In [30]:
lab_df = df[['id', 'chol', 'weight', 'height']].loc[2:7]
lab_df

     id   chol  weight  height
2  1002  228.0   256.0    61.0
3  1003   78.0   119.0    67.0
4  1005  249.0   183.0    68.0
5  1008  248.0   190.0    71.0
6  1011  195.0   191.0    69.0
7  1015  227.0   170.0    59.0

In [31]:
temp = pd.concat([patient_df, lab_df])

In [32]:
temp

     id   age  gender   chol  weight  height
0  1000  46.0  female    NaN     NaN     NaN
1  1001  29.0  female    NaN     NaN     NaN
2  1002  58.0  female    NaN     NaN     NaN
3  1003  67.0    male    NaN     NaN     NaN
4  1005  64.0    male    NaN     NaN     NaN
5  1008  34.0    male    NaN     NaN     NaN
2  1002   NaN     NaN  228.0   256.0    61.0
3  1003   NaN     NaN   78.0   119.0    67.0
4  1005   NaN     NaN  249.0   183.0    68.0
5  1008   NaN     NaN  248.0   190.0    71.0
6  1011   NaN     NaN  195.0   191.0    69.0
7  1015   NaN     NaN  227.0   170.0    59.0

## Inner Join

In [33]:
result_df = pd.merge(patient_df, lab_df, how='inner', left_on='id', right_on='id')
result_df

     id  age  gender   chol  weight  height
0  1002   58  female  228.0   256.0    61.0
1  1003   67    male   78.0   119.0    67.0
2  1005   64    male  249.0   183.0    68.0
3  1008   34    male  248.0   190.0    71.0

## Left Join

In [34]:
result_df = pd.merge(patient_df, lab_df, how='left', left_on='id', right_on='id')
result_df

     id  age  gender   chol  weight  height
0  1000   46  female    NaN     NaN     NaN
1  1001   29  female    NaN     NaN     NaN
2  1002   58  female  228.0   256.0    61.0
3  1003   67    male   78.0   119.0    67.0
4  1005   64    male  249.0   183.0    68.0
5  1008   34    male  248.0   190.0    71.0

## Right Join (useless)

In [35]:
result_df = pd.merge(patient_df, lab_df, how='right', left_on='id', right_on='id')
result_df

     id   age  gender   chol  weight  height
0  1002  58.0  female  228.0   256.0    61.0
1  1003  67.0    male   78.0   119.0    67.0
2  1005  64.0    male  249.0   183.0    68.0
3  1008  34.0    male  248.0   190.0    71.0
4  1011   NaN     NaN  195.0   191.0    69.0
5  1015   NaN     NaN  227.0   170.0    59.0

In [37]:
# You can achieve the same thing by simply switching the order of tables
result_df = pd.merge(lab_df, patient_df, how='left', left_on='id', right_on='id')
result_df

     id   chol  weight  height   age  gender
0  1002  228.0   256.0    61.0  58.0  female
1  1003   78.0   119.0    67.0  67.0    male
2  1005  249.0   183.0    68.0  64.0    male
3  1008  248.0   190.0    71.0  34.0    male
4  1011  195.0   191.0    69.0   NaN     NaN
5  1015  227.0   170.0    59.0   NaN     NaN

## Full (or Outer) Join

In [38]:
result_df = pd.merge(lab_df, patient_df, how='outer', left_on='id', right_on='id')
result_df

     id   chol  weight  height   age  gender
0  1000    NaN     NaN     NaN  46.0  female
1  1001    NaN     NaN     NaN  29.0  female
2  1002  228.0   256.0    61.0  58.0  female
3  1003   78.0   119.0    67.0  67.0    male
4  1005  249.0   183.0    68.0  64.0    male
5  1008  248.0   190.0    71.0  34.0    male
6  1011  195.0   191.0    69.0   NaN     NaN
7  1015  227.0   170.0    59.0   NaN     NaN

## Example with key columns named differently

In [39]:
country_df = pd.read_csv('country.csv')
city_df = pd.read_csv('city.csv')

In [40]:
country_df.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,JosÃ© Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,ShqipÃ«ria,Republic,Rexhep Mejdani,34.0,AL

In [41]:
city_df.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [42]:
geo_df = pd.merge(country_df, city_df, how='inner', left_on='Code', right_on='CountryCode')
geo_df.head()

,Code,Name_x,Continent,Region,SurfaceArea,IndepYear,Population_x,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,ID,Name_y,CountryCode,District,Population_y
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW,129,Oranjestad,ABW,â€“,29034
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,1,Kabul,AFG,Kabol,1780000
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,2,Qandahar,AFG,Qandahar,237500
3,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,3,Herat,AFG,Herat,186800
4,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,4,Mazar-e-Sharif,AFG,Balkh,127800

## Statistics

In [43]:
df = pd.read_csv('diabetes.csv')

In [44]:
df.describe()

,id,chol,stab.glu,hdl,ratio,glyhb,age,height,weight,bp.1s,bp.1d,waist,hip
count,403.000000,402.000000,403.000000,402.000000,402.000000,390.000000,403.000000,398.000000,402.000000,398.000000,398.000000,401.000000,401.000000
mean,15978.310174,207.845771,106.672457,50.445274,4.521642,5.589769,46.851117,66.020101,177.592040,136.904523,83.321608,37.900249,43.039900
std,11881.122124,44.445557,53.076655,17.262626,1.727886,2.242595,16.312333,3.918515,40.340666,22.741033,13.589227,5.729313,5.656713
min,1000.000000,78.000000,48.000000,12.000000,1.500000,2.680000,19.000000,52.000000,99.000000,90.000000,48.000000,26.000000,30.000000
25%,4792.500000,179.000000,81.000000,38.000000,3.200000,4.380000,34.000000,63.000000,151.000000,121.250000,75.000000,33.000000,39.000000
50%,15766.000000,204.000000,89.000000,46.000000,4.200000,4.840000,45.000000,66.000000,172.500000,136.000000,82.000000,37.000000,42.000000
75%,20336.000000,230.000000,106.000000,59.000000,5.400000,5.600000,60.000000,69.000000,200.000000,146.750000,90.000000,41.000000,46.000000
max,41756.000000,443.000000,385.000000,120.000000,19.299999,16.110001,92.000000,76.000000,325.000000,250.000000,124.000000,56.000000,64.000000

In [45]:
df.shape

(403, 16)

In [46]:
df.dtypes

id            int64
chol        float64
stab.glu      int64
hdl         float64
ratio       float64
glyhb       float64
location        str
age           int64
gender          str
height      float64
weight      float64
frame           str
bp.1s       float64
bp.1d       float64
waist       float64
hip         float64
dtype: object

In [47]:
a = "10000"
b = "7,345.55"
a + b

'100007,345.55'

In [49]:
df['age'].mean()

np.float64(46.851116625310176)

In [50]:
df['age'].median()

np.float64(45.0)

In [51]:
df['age'].min()

np.int64(19)

In [52]:
df['age'].max()

np.int64(92)

In [53]:
df['age'].sum()

np.int64(18881)

In [54]:
df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
398      male
399    female
400    female
401    female
402    female
Name: gender, Length: 403, dtype: str

In [55]:
df['gender'].sum()

'femalefemalefemalemalemalemalemalemalemalefemalefemalefemalefemalefemalemalefemalefemalemalemalefemalemalemalefemalefemalefemalefemalemalemalefemalemalefemalemalemalefemalemalefemalemalemalemalemalefemalefemalemalemalefemalefemalefemalemalefemalefemalemalefemalefemalefemalefemalefemalemalefemalefemalefemalefemalemalefemalefemalemalefemalefemalefemalefemalefemalemalefemalefemalefemalemalefemalefemalemalefemalefemalemalefemalemalefemalefemalemalefemalefemalefemalemalemalefemalefemalemalefemalefemalefemalefemalefemalemalefemalemalefemalemalefemalemalefemalefemalemalemalemalemalemalefemalefemalemalefemalefemalemalemalemalefemalemalefemalemalefemalefemalefemalefemalemalefemalefemalefemalefemalefemalefemalemalefemalemalemalefemalefemalefemalemalefemalemalemalemalefemalemalemalefemalemalemalefemalemalemalefemalemalefemalemalemalefemalefemalefemalefemalemalefemalefemalefemalefemalefemalemalemalefemalemalefemalefemalemalemalefemalemalefemalemalemalefemalemalemalefemalefemalefemalefemalemalefemalemalefemalefemalemalefemalemalefemalefemalemalefemalemalemalemalefemalefemalefemalemalefemalefemalemalemalefemalefemalemalefemalefemalefemalefemalemalefemalefemalemalefemalefemalemalefemalemalefemalemalemalefemalemalefemalemalemalefemalemalefemalemalefemalemalefemalefemalefemalefemalefemalefemalefemalefemalemalefemalefemalefemalemalefemalemalemalemalemalefemalemalefemalefemalemalemalefemalemalemalefemalefemalefemalefemalemalefemalefemalemalefemalemalefemalemalefemalefemalefemalefemalemalefemalemalemalefemalemalemalemalefemalefemalefemalefemalefemalefemalefemalefemalefemalemalefemalefemalefemalemalefemalefemalemalemalemalefemalefemalefemalefemalemalemalefemalemalemalemalemalemalemalefemalemalemalefemalefemalemalefemalemalefemalefemalefemalefemalemalefemalefemalefemalefemalefemalefemalemalefemalemalemalefemalemalemalefemalemalemalemalemalemalefemalefemalefemalefemalefemalefemalemalemalefemalefemalefemalefemalefemalefemalemalemalemalemalemalefemalefemalemalefemalemalemalefemalefemalefemalemalemalefemalefemalemalemalefemalemalefemalefemalemalefemalefemalefemalefemale'

In [56]:
df.head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0

In [57]:
df.shape

(403, 16)

In [59]:
df.dtypes

id            int64
chol        float64
stab.glu      int64
hdl         float64
ratio       float64
glyhb       float64
location        str
age           int64
gender          str
height      float64
weight      float64
frame           str
bp.1s       float64
bp.1d       float64
waist       float64
hip         float64
dtype: object

In [63]:
x = 5
y = 10
z = 5

In [64]:
x == y

False

In [65]:
(x == y) or (x == z)

True

In [66]:
df.head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0

In [67]:
q = "chol > 200"
df.query(q)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.310000,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0
5,1008,248.0,94,69.0,3.6,4.810000,Buckingham,34,male,71.0,190.0,large,132.0,86.0,36.0,42.0
7,1015,227.0,75,44.0,5.2,3.940000,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,34.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,41078,210.0,81,81.0,2.6,4.960000,Louisa,78,male,66.0,145.0,large,110.0,70.0,38.0,39.0
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,38.0,42.0
397,41503,301.0,90,118.0,2.6,4.280000,Louisa,89,female,61.0,115.0,medium,218.0,90.0,31.0,41.0
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,35.0,39.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,32.0,43.0

In [68]:
df.query("chol > 200")

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.310000,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0
5,1008,248.0,94,69.0,3.6,4.810000,Buckingham,34,male,71.0,190.0,large,132.0,86.0,36.0,42.0
7,1015,227.0,75,44.0,5.2,3.940000,Buckingham,37,male,59.0,170.0,medium,NaN,NaN,34.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,41078,210.0,81,81.0,2.6,4.960000,Louisa,78,male,66.0,145.0,large,110.0,70.0,38.0,39.0
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,38.0,42.0
397,41503,301.0,90,118.0,2.6,4.280000,Louisa,89,female,61.0,115.0,medium,218.0,90.0,31.0,41.0
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,35.0,39.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,32.0,43.0

In [69]:
df.query("chol > 200 and gender == 'female'")

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0
9,1022,263.0,89,40.0,6.6,5.78,Buckingham,55,female,63.0,202.0,small,108.0,72.0,45.0,50.0
10,1024,242.0,82,54.0,4.5,4.77,Louisa,60,female,65.0,156.0,medium,130.0,90.0,39.0,45.0
11,1029,215.0,128,34.0,6.3,4.97,Louisa,38,female,58.0,195.0,medium,102.0,68.0,42.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,41041,279.0,270,40.0,7.0,8.11,Louisa,60,female,68.0,224.0,large,174.0,90.0,48.0,50.0
391,41075,221.0,126,48.0,4.6,5.53,Louisa,59,female,62.0,177.0,medium,130.0,78.0,39.0,45.0
396,41501,216.0,84,64.0,3.4,NaN,Louisa,54,female,66.0,168.0,medium,132.0,90.0,38.0,42.0
397,41503,301.0,90,118.0,2.6,4.28,Louisa,89,female,61.0,115.0,medium,218.0,90.0,31.0,41.0
399,41507,284.0,89,54.0,5.3,4.39,Louisa,51,female,63.0,154.0,medium,140.0,100.0,32.0,43.0

In [71]:
df.query("chol > 200 and gender == 'female' and weight < 120")

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip
24,1271,228.0,66,45.0,5.1,4.61,Buckingham,24,female,61.0,113.0,medium,100.0,70.0,33.0,38.0
191,15540,236.0,111,82.0,2.9,5.24,Louisa,68,female,61.0,119.0,small,142.0,96.0,29.0,37.0
200,15763,271.0,103,90.0,3.0,4.01,Buckingham,55,female,63.0,114.0,small,180.0,105.0,30.0,37.0
227,16001,222.0,82,87.0,2.6,4.64,Buckingham,51,female,66.0,110.0,small,150.0,110.0,28.0,37.0
302,20337,226.0,97,70.0,3.2,3.88,Louisa,20,female,64.0,114.0,small,122.0,64.0,31.0,39.0
397,41503,301.0,90,118.0,2.6,4.28,Louisa,89,female,61.0,115.0,medium,218.0,90.0,31.0,41.0

In [74]:
df.query("chol > 200 and gender == 'female' and weight < 120")[['id', 'age', 'chol', 'weight']]

        id  age   chol  weight
24    1271   24  228.0   113.0
191  15540   68  236.0   119.0
200  15763   55  271.0   114.0
227  16001   51  222.0   110.0
302  20337   20  226.0   114.0
397  41503   89  301.0   115.0

In [75]:
df.query("chol > 200 and gender == 'female' and weight < 120")[['id', 'age', 'chol', 'weight']].sort_values('age')

        id  age   chol  weight
302  20337   20  226.0   114.0
24    1271   24  228.0   113.0
227  16001   51  222.0   110.0
200  15763   55  271.0   114.0
191  15540   68  236.0   119.0
397  41503   89  301.0   115.0

In [76]:
df.query("chol > 200 and gender == 'female' and weight < 120")[['id', 'age', 'chol', 'weight']].sort_values('age', ascending=False)

        id  age   chol  weight
397  41503   89  301.0   115.0
191  15540   68  236.0   119.0
200  15763   55  271.0   114.0
227  16001   51  222.0   110.0
24    1271   24  228.0   113.0
302  20337   20  226.0   114.0